version: '3'

services: 
  prisma:
    ports:
      - 4466:4466
  backend: 
    build: 
      context: .
      dockerfile: dockerfile-dev
    image: graphql-backend-dev
    ports: 
      - 4000:4000
    volumes: 
      - .:/opt/app
    environment: 
      NODE_ENV: development
    command: bash /wait-for-it.sh -t 30 prisma:4466 -- sh -c 'yarn && yarn prisma-deploy && yarn start'